/**
 * Automatically generated by @grafana/openapi-to-k6: 0.3.2
 * Do not edit manually.
 * Restaures-Services
 * Service version: 1.0.0
 */
import { FormData } from "https://jslib.k6.io/formdata/0.0.2/index.js";

import { URL } from "https://jslib.k6.io/url/1.0.0/index.js";

import http from "k6/http";
import type { Params, Response } from "k6/http";

export type PostApiCustomerLoginBody = {
  email: string;
  /** @minLength 6 */
  password: string;
};

export type PostApiCustomerRegisterBody = {
  /** @minLength 1 */
  firstName: string;
  lastName?: string;
  email: string;
  /** @minLength 1 */
  phoneNumber: string;
  /** @minLength 1 */
  password: string;
  profilePicture?: string;
};

export type PostApiUploadFileBody = {
  file?: Blob;
  files?: Blob[];
  filePath?: string;
  metadata?: string;
  fileName?: string;
  contentType?: string;
};

export type PostApiRefreshBody = {
  refresh_token: string;
};

export type PostApiRestaurantRegisterBodyLocation = {
  /** @minLength 1 */
  address: string;
  /** @minLength 1 */
  city: string;
  /** @minLength 1 */
  state: string;
  /** @minLength 1 */
  zipCode: string;
  /** @minLength 1 */
  country: string;
  latitude?: number;
  longitude?: number;
};

export type PostApiRestaurantRegisterBodyWorkingDaysItem = {
  /** @minLength 1 */
  days: string;
  /** @minLength 1 */
  openingTime: string;
  /** @minLength 1 */
  closingTime: string;
};

export type PostApiRestaurantRegisterBodyOwner = {
  /** @minLength 1 */
  name: string;
  /** @minLength 10 */
  phone: string;
  email: string;
};

export type PostApiRestaurantRegisterBodyBankDetails = {
  /** @minLength 1 */
  ifsc: string;
  /** @minLength 1 */
  accountNumber: string;
};

export type PostApiRestaurantRegisterBody = {
  /** @minLength 1 */
  name: string;
  /** @minLength 10 */
  managementPhone: string;
  restaurantEmail: string;
  location: PostApiRestaurantRegisterBodyLocation;
  workingDays: PostApiRestaurantRegisterBodyWorkingDaysItem[];
  images?: string[];
  owner: PostApiRestaurantRegisterBodyOwner;
  /** @minLength 1 */
  panNumber: string;
  /** @minLength 1 */
  gstinNumber: string;
  bankDetails: PostApiRestaurantRegisterBodyBankDetails;
  /** @minLength 1 */
  fssaiRegistrationNumber: string;
  /** @minLength 6 */
  password: string;
};

export type PostApiRestaurantLoginBody = {
  email: string;
  /** @minLength 1 */
  password: string;
};

export type PostApiRestaurantMenuBody = {
  /** @minLength 1 */
  name: string;
  description?: string;
  images?: string[];
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  price: number;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  timeToPrepare: number;
  /** @minLength 1 */
  category: string;
};

export type PostApiCustomerEnquiryBody = {
  /** @minLength 1 */
  menuId: string;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  quantity: number;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  totalPrice: number;
};

export type PutApiRestaurantEnquiryStatusIdBody = {
  /** @minLength 1 */
  status: string;
  /**
   * @minimum 0
   * @exclusiveMinimum
   */
  timeToPrepare?: number;
};

export type PutApiCustomerMenuRateIdBody = {
  /**
   * @minimum 1
   * @maximum 5
   */
  rating: number;
};

/**
 * This is the base client to use for interacting with the API.
 */
export class RestauresServicesClient {
  private cleanBaseUrl: string;
  private commonRequestParameters: Params;

  constructor(clientOptions: {
    baseUrl: string;
    commonRequestParameters?: Params;
  }) {
    this.cleanBaseUrl = clientOptions.baseUrl.replace(/\/+$/, "");

    this.commonRequestParameters = clientOptions.commonRequestParameters || {};
  }

  /**
   * @summary Login Customer
   */
  postApiCustomerLogin(
    postApiCustomerLoginBody: PostApiCustomerLoginBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/api/customer/login`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postApiCustomerLoginBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;

    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Register Customer
   */
  postApiCustomerRegister(
    postApiCustomerRegisterBody: PostApiCustomerRegisterBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/api/customer/register`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postApiCustomerRegisterBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary allocate restaurant
   */
  postApiUploadFile(
    postApiUploadFileBody: PostApiUploadFileBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const formData = new FormData();
    if (postApiUploadFileBody.file !== undefined) {
      formData.append("file", postApiUploadFileBody.file);
    }
    if (postApiUploadFileBody.files !== undefined) {
      postApiUploadFileBody.files.forEach((value) =>
        formData.append("files", value),
      );
    }
    if (postApiUploadFileBody.filePath !== undefined) {
      formData.append("filePath", postApiUploadFileBody.filePath);
    }
    if (postApiUploadFileBody.metadata !== undefined) {
      formData.append("metadata", postApiUploadFileBody.metadata);
    }
    if (postApiUploadFileBody.fileName !== undefined) {
      formData.append("fileName", postApiUploadFileBody.fileName);
    }
    if (postApiUploadFileBody.contentType !== undefined) {
      formData.append("contentType", postApiUploadFileBody.contentType);
    }

    const url = new URL(this.cleanBaseUrl + `/api/upload-file`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request("POST", url.toString(), formData.body(), {
      ...mergedRequestParameters,
      headers: {
        ...mergedRequestParameters?.headers,
        "Content-Type": "multipart/form-data; boundary=" + formData.boundary,
      },
    });
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Login
   */
  postApiRefresh(
    postApiRefreshBody: PostApiRefreshBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/api/refresh`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postApiRefreshBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Register Restaurant
   */
  postApiRestaurantRegister(
    postApiRestaurantRegisterBody: PostApiRestaurantRegisterBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/api/restaurant/register`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postApiRestaurantRegisterBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Login Restaurant
   */
  postApiRestaurantLogin(
    postApiRestaurantLoginBody: PostApiRestaurantLoginBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/api/restaurant/login`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postApiRestaurantLoginBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Add Menu
   */
  postApiRestaurantMenu(
    postApiRestaurantMenuBody: PostApiRestaurantMenuBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/api/restaurant/menu`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postApiRestaurantMenuBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Get Menu
   */
  getApiMenu(requestParameters?: Params): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/api/menu`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Get Menu By Id
   */
  getApiMenuId(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/api/menu/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Get Menu By Restaurant Id
   */
  getApiMenuRestaurantRestaurantId(
    restaurantId: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(
      this.cleanBaseUrl + `/api/menu/restaurant/${restaurantId}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Get Restaurant
   */
  getApiCustomerRestaurant(requestParameters?: Params): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/api/customer/restaurant`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Get Restaurant By Id
   */
  getApiCustomerRestaurantId(
    id: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/api/customer/restaurant/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Add Favorite Restaurant
   */
  putApiCustomerFavoriteRestaurantRestaurantId(
    restaurantId: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(
      this.cleanBaseUrl + `/api/customer/favorite/restaurant/${restaurantId}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "PUT",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Delete Favorite Restaurant
   */
  deleteApiCustomerFavoriteRestaurantRestaurantId(
    restaurantId: string,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(
      this.cleanBaseUrl + `/api/customer/favorite/restaurant/${restaurantId}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "DELETE",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Get Favorite Restaurants
   */
  getApiCustomerFavoriteRestaurant(requestParameters?: Params): {
    response: Response;
    data: void;
  } {
    const url = new URL(
      this.cleanBaseUrl + `/api/customer/favorite/restaurant`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Add Enquiry
   */
  postApiCustomerEnquiry(
    postApiCustomerEnquiryBody: PostApiCustomerEnquiryBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/api/customer/enquiry`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "POST",
      url.toString(),
      JSON.stringify(postApiCustomerEnquiryBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Get Enquiries
   */
  getApiCustomerEnquiry(requestParameters?: Params): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/api/customer/enquiry`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Get Enquiries
   */
  getApiRestaurantEnquiry(requestParameters?: Params): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/api/restaurant/enquiry`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "GET",
      url.toString(),
      undefined,
      mergedRequestParameters,
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Update Enquiry Status
   */
  putApiRestaurantEnquiryStatusId(
    id: string,
    putApiRestaurantEnquiryStatusIdBody: PutApiRestaurantEnquiryStatusIdBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(
      this.cleanBaseUrl + `/api/restaurant/enquiry/status/${id}`,
    );
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "PUT",
      url.toString(),
      JSON.stringify(putApiRestaurantEnquiryStatusIdBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * @summary Rate Enquiry
   */
  putApiCustomerMenuRateId(
    id: string,
    putApiCustomerMenuRateIdBody: PutApiCustomerMenuRateIdBody,
    requestParameters?: Params,
  ): {
    response: Response;
    data: void;
  } {
    const url = new URL(this.cleanBaseUrl + `/api/customer/menu/rate/${id}`);
    const mergedRequestParameters = this._mergeRequestParameters(
      requestParameters || {},
      this.commonRequestParameters,
    );
    const response = http.request(
      "PUT",
      url.toString(),
      JSON.stringify(putApiCustomerMenuRateIdBody),
      {
        ...mergedRequestParameters,
        headers: {
          ...mergedRequestParameters?.headers,
          "Content-Type": "application/json",
        },
      },
    );
    let data;

    try {
      data = response.json();
    } catch {
      data = response.body;
    }
    return {
      response,
      data,
    };
  }

  /**
   * Merges the provided request parameters with default parameters for the client.
   *
   * @param {Params} requestParameters - The parameters provided specifically for the request
   * @param {Params} commonRequestParameters - Common parameters for all requests
   * @returns {Params} - The merged parameters
   */
  private _mergeRequestParameters(
    requestParameters?: Params,
    commonRequestParameters?: Params,
  ): Params {
    return {
      ...commonRequestParameters, // Default to common parameters
      ...requestParameters, // Override with request-specific parameters
      headers: {
        ...(commonRequestParameters?.headers || {}), // Ensure headers are defined
        ...(requestParameters?.headers || {}),
      },
      cookies: {
        ...(commonRequestParameters?.cookies || {}), // Ensure cookies are defined
        ...(requestParameters?.cookies || {}),
      },
      tags: {
        ...(commonRequestParameters?.tags || {}), // Ensure tags are defined
        ...(requestParameters?.tags || {}),
      },
    };
  }
}
